version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  nginx-rtmp:
    build:
      context: "./nginx-rtmp/"
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf